source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GSPDSegmentedBarView_Example', :exclusive => true do
  pod "GSPDSegmentedBarView", :path => "../"
end

target 'GSPDSegmentedBarView_Tests', :exclusive => true do
  pod "GSPDSegmentedBarView", :path => "../"

  
end
